//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardiRecords.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedTypesForUser
    {
        public System.Guid id { get; set; }
        public System.Guid recordTypeId { get; set; }
        public System.Guid userId { get; set; }
        public System.Guid createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.Guid modifyBy { get; set; }
        public System.DateTime modifyDate { get; set; }
    
        public virtual RecordType RecordType { get; set; }
    }
}
