//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardiRecords.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBs()
        {
            this.BackupLocations = new HashSet<BackupLocations>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid recordListId { get; set; }
        public bool isActive { get; set; }
        public bool isBackup { get; set; }
        public bool isArchived { get; set; }
        public string phisicalPath { get; set; }
        public int sqlType { get; set; }
        public int sqlVersion { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifyBy { get; set; }
        public System.DateTime modifyDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackupLocations> BackupLocations { get; set; }
    }
}
