//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardiRecords.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TardiRecordsEntities : DbContext
    {
        public TardiRecordsEntities()
            : base("name=TardiRecordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AllowedTypesForUser> AllowedTypesForUser { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BackupLocations> BackupLocations { get; set; }
        public virtual DbSet<DBs> DBs { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachinesInUse> MachinesInUse { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<RecordList> RecordList { get; set; }
        public virtual DbSet<RecordType> RecordType { get; set; }
    }
}
