//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardiRecords.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllUsers
    {
        public string AspNetUserId { get; set; }
        public System.Guid AppUserId { get; set; }
        public string Email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string position { get; set; }
        public System.DateTime modifyDate { get; set; }
        public bool LockoutEnabled { get; set; }
        public string EditedBy { get; set; }
    }
}
