//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardiRecords.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RecordListDetails
    {
        public System.Guid id { get; set; }
        public System.Guid BackupLocationsId { get; set; }
        public System.Guid FilesId { get; set; }
        public System.Guid NotesId { get; set; }
        public System.Guid Dbid { get; set; }
        public string title { get; set; }
        public string fullName { get; set; }
        public string path { get; set; }
        public System.DateTime modifyDate { get; set; }
        public string noteText { get; set; }
        public string createdBy { get; set; }
        public bool isActive { get; set; }
        public bool isBackup { get; set; }
        public bool isArchived { get; set; }
        public string phisicalPath { get; set; }
        public int sqlType { get; set; }
        public int sqlVersion { get; set; }
        public string modifyBy { get; set; }
        public System.DateTime Expr5 { get; set; }
        public System.DateTime Expr6 { get; set; }
        public string Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public System.DateTime Expr10 { get; set; }
    }
}
